---
- name: Configure /etc/hosts for localhost
  hosts: all
  gather_facts: no
  tasks:

  - name: "Configure /etc/hosts"
    lineinfile:
      regexp: '^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3} {{ inventory_hostname }}$'
      line: "{{ ansible_ssh_host }} {{ inventory_hostname }}"
      state: present
      path: /etc/hosts
    delegate_to: localhost
    become: true
