---
- name: Configure VM host
  hosts: all
  become: true
  tasks:
  - name: "Configure /etc/hosts"
    lineinfile:
      regexp: '^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3} {{ ansible_hostname }}$'
      line: "{{ ansible_ssh_host }} {{ ansible_hostname }}"
      state: present
      path: /etc/hosts
    delegate_to: localhost
