ansible_connection: ssh
ansible_user: vagrant
vagrant_provider: virtualbox
# disabled with ubuntu/focal64 ("PasswordAuthentication no" in /etc/ssh/sshd_config)
# ansible_ssh_pass=vagrant
ansible_ssh_private_key_file: "{{ inventory_dir }}/../.vagrant/machines/{{ inventory_hostname }}/{{ vagrant_provider }}/private_key"
