# server or agent
k3s_mode: server
# required for agent
k3s_url: ~
k3s_token: ~
# command line opts (ex : '--disable traefik --write-kubeconfig-mode 644')
k3s_installer_opts: ''
# ex : 'v1.24'
k3s_channel: 'stable'
