---
- name: Configure /etc/hosts for localhost
  hosts: all
  gather_facts: no
  vars:
    configure_host_enabled: true
  tasks:

  - name: "Configure /etc/hosts"
    lineinfile:
      regexp: '^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3} {{ inventory_hostname }}$'
      line: "{{ ansible_ssh_host }} {{ inventory_hostname }}"
      state: present
      path: /etc/hosts
    throttle: 1
    delegate_to: localhost
    become: true
    when: configure_host_enabled|bool
